CREATE DATABASE nnstats DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE nnstats;
DROP TABLE IF EXISTS `stats`;
CREATE TABLE `stats` (
	`categoryID` INT DEFAULT 0,
	`categoryname` VARCHAR(255) NOT NULL DEFAULT '',
	`updatedate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`ppqcount` INT DEFAULT 0,
	`nullnfo` INT DEFAULT 0,
	PRIMARY KEY (`categoryID`)
) ENGINE=MYISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci